### ISSUE TITLE
`dprint` not available in Package Control

### ISSUE THREAD

**Issue by dalisoft** [dprint/dprint-sublime#4]
Hi @dsherret 

I tried install package via Package control and it did not found, so i looked at [here](https://packagecontrol.io/packages/dprint) and seems error 404, can you look please if you can find time?

**Comment by dsherret** [comment]
Sorry, I never actually ended up getting this on package control. There were some outstanding issues:

https://github.com/wbond/package_control_channel/pull/7969#issuecomment-674027696

**Comment by dalisoft** [comment]
@dsherret Thanks for quick reply and link. Seems currently solution is installing via `git`.

Steps:
1. Open Sublime Text
2. Cmd/Ctrl + Shift + P
3. Browse Packages
4. Open terminal in directory
5. Clone this repository to that directory

It works for me and should work for everyone.

Have a nice day!
Happy new year!

Regards,
Davlik

**Comment by KyGost** [comment]
@dalisoft did the package end up actually working? Upon installing no commands seem to become available for me.

**Comment by imjordanxd** [comment]
Anyone manage to get this working?

**Comment by rope-hmg** [comment]
When cloning to the `Packages` directory and restarting sublime I see the following error in the sublime console:

```
Sublime Version: Dev Channel, Build 4114
```

```
reloading python 3.3 plugin dprint-sublime.dprint
Traceback (most recent call last):
  File "/Applications/Sublime Text (4109).app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 308, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/username/Library/Application Support/Sublime Text 3/Packages/dprint-sublime/dprint.py", line 8, in <module>
    dprint_exec = DprintExec()
NameError: name 'DprintExec' is not defined
```

I'm not familiar with the sublime plugin api, so this doesn't really mean anything to me.

Thanks

**Comment by rope-hmg** [comment]
So I've done some investigating and it looks like there are a few problems.

```python
json_text = subprocess.check_output(["dprint", "editor-info"], cwd=dir_path, shell=True).decode("utf8")
```
If I change `"dprint", "editor-info"` to `"dprint editor-info"` then it work, but it complains about the schema version. The plugin lists it as `1`, but the `editor-info` is coming back with `4`.

If I change that to `4` then I can format, but it writes the dprint help text to the buffer.

The issue is again with the array arguments in 
```python
p = Popen(["dprint", "stdin-fmt", "--file-name", os.path.basename(file_path)],
			stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=dir_path, shell=True)
```

If I merge them again I dprint complains with `error: Found argument 'stdin-fmt' which wasn't expected, or isn't valid in this context`

**Comment by rope-hmg** [comment]
One other thing I forgot.

I had to move the line

```python
dprint_exec = DprintExec()
```

to the bottom of the file.

**Comment by rope-hmg** [comment]
Update:

Removed `shell=True` from the commands:

```python
json_text = subprocess.check_output(["dprint", "editor-info"], cwd=dir_path).decode("utf8")
```

Also looked at dprint src to find out why `fmt-stdin` wasn't working.

```python
p = Popen(["dprint", "fmt", "stdin", os.path.basename(file_path)],
			stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd=dir_path)
```
I've reached the point where the problem is with:

```python
print("#----------", file_text)
stdout, stderr = p.communicate(bytes(file_text, "utf8"))
print("#----------", stdout)
```

`file_text` looks correct, but `stdout` is just `b'Formatted \x1b[1m1\x1b[0m file.\n'`

**Comment by rope-hmg** [comment]
So. Turns out I misread the code. Should have been `--stdin` in `Popen`. It's working fine now. I'll make a PR.

**Comment by dsherret** [comment]
Thanks for the help @rope-hmg! I opened https://github.com/wbond/package_control_channel/pull/8509
